name: Build a WAR file using Maven
on:
  push: 
    branches: ["main"]
jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install -f MyWebApp/pom.xml
      - name: Print Current Working Directory
        run: pwd
      - name: Deploy to Tomcat
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
          -T MyWebApp/target/MyWebApp.war \
          "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/MyWebApp&update=true"
      - name: Upload WAR to Nexus
        run: |
          curl -v -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASSWORD }} \
          --upload-file MyWebApp/target/MyWebApp.war \
          http://ec2-34-236-148-33.compute-1.amazonaws.com:8081/maven-snapshots:com/gcp/myapp-1.0.0.war
      - uses: act10ns/slack@v2
        with:
          channel: '#dec-2024-weekday-batch'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
