name: Build a WAR file using Maven
on:
  push: 
    branches: ["main"]
jobs:
  build: 
    runs-on: ubuntu-24.0.4
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install -f MyWebApp/pom.xml
      - name: Deploy to Tomcat
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
          -T target/*.war \
          "http://ec2-54-234-97-11.compute-1.amazonaws.com:8090/manager/text/deploy?path=/MyWebApp&update=true"
          
      - uses: act10ns/slack@v2
        with:
          channel: '#dec-2024-weekday-batch'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
